# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совмместного разбора

In [1]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
arr1 = np.random.uniform(0,20, size=(4,7))
ar2 = [(i - arr1.min()) / (arr1.max() - arr1.min()) for i in arr1]
ar3 = [(i - np.min(arr1)) / (np.max(arr1) - np.min(arr1)) for i in arr1]
print(ar2)
print()
print(ar3)

[array([0.61411676, 0.21190286, 0.89482836, 0.16604413, 0.65751693,
       0.29240575, 0.27669171]), array([0.62789805, 0.89287017, 0.45600321, 0.39629224, 0.        ,
       0.53927689, 0.00903547]), array([0.91326599, 0.28452538, 0.56908382, 0.37375266, 0.52808817,
       1.        , 0.57149316]), array([0.5314684 , 0.47939001, 0.55382301, 0.50312112, 0.85562091,
       0.23696945, 0.3038262 ])]

[array([0.61411676, 0.21190286, 0.89482836, 0.16604413, 0.65751693,
       0.29240575, 0.27669171]), array([0.62789805, 0.89287017, 0.45600321, 0.39629224, 0.        ,
       0.53927689, 0.00903547]), array([0.91326599, 0.28452538, 0.56908382, 0.37375266, 0.52808817,
       1.        , 0.57149316]), array([0.5314684 , 0.47939001, 0.55382301, 0.50312112, 0.85562091,
       0.23696945, 0.3038262 ])]


In [3]:
(arr1 - np.min(arr1)) / (np.max(arr1) - np.min(arr1))

array([[0.61411676, 0.21190286, 0.89482836, 0.16604413, 0.65751693,
        0.29240575, 0.27669171],
       [0.62789805, 0.89287017, 0.45600321, 0.39629224, 0.        ,
        0.53927689, 0.00903547],
       [0.91326599, 0.28452538, 0.56908382, 0.37375266, 0.52808817,
        1.        , 0.57149316],
       [0.5314684 , 0.47939001, 0.55382301, 0.50312112, 0.85562091,
        0.23696945, 0.3038262 ]])

In [4]:
arr1.max(axis=1)

array([18.01429781, 17.97766953, 19.9815568 , 17.28091376])

In [5]:
arr1.max(axis=0)

array([18.35917778, 17.97766953, 18.01429781, 10.68732659, 17.28091376,
       19.9815568 , 11.96624092])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
arr2 = np.random.randint(0,11, size=(8,10))
arr2

array([[ 2,  7,  9,  8,  6, 10,  3,  7,  1,  7],
       [ 5,  0,  7,  5,  7,  3,  5,  9,  3,  2],
       [ 4,  8,  0, 10,  9,  7,  9,  0,  8,  2],
       [ 1,  6,  4,  5,  9,  1,  1, 10,  3,  2],
       [ 9,  6,  3,  5,  5,  1,  5,  1,  6,  2],
       [ 9,  8,  6,  5, 10,  9,  4,  5,  9,  3],
       [ 6,  0,  2,  3,  6,  8,  1,  2,  4,  1],
       [ 6,  6,  7, 10,  3,  5,  8, 10,  9,  9]])

In [7]:
msk = arr2.sum(axis=1) == np.max(arr2.sum(axis=1))
arr2[msk]

array([[ 6,  6,  7, 10,  3,  5,  8, 10,  9,  9]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [8]:
v1 = np.random.randint(0,10, size=(8,))
v2 = np.random.randint(0,10, size=(8,))
print(v1)
print(v2)

[2 0 8 3 0 6 2 9]
[3 9 1 0 4 3 4 5]


In [9]:
np.sqrt(np.sum((v1 - v2)**2))

13.601470508735444

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [10]:
a = np.array([-1, 2, 4, -3, 1, 2, -3, 0, 1]).reshape(3,3)
b = np.array([3, -1, 2, 1]).reshape(2,2)
c = np.array([7, 21, 11, 8, 8, 4]).reshape(3,2)

x = np.dot(np.dot(np.linalg.inv(a), c * (-1)), np.linalg.inv(b))
x1 = np.linalg.inv(a) @ -c @ np.linalg.inv(b)
x1

#X = A^(-1) x (-C) x B^(-1)


array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [11]:
minutes_n_ingredients = np.loadtxt('./data/minutes_n_ingredients.csv', dtype='int32', skiprows=1, delimiter=',')
minutes_n_ingredients[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [12]:
np.mean(minutes_n_ingredients[:,1:], axis=0) # cреднее v1

array([2.16010017e+04, 9.05528000e+00])

In [13]:
np.average(minutes_n_ingredients[:,1:], axis=0) # cреднее v2

array([2.16010017e+04, 9.05528000e+00])

In [14]:
np.min(minutes_n_ingredients[:,1:], axis=0) #минимум

array([0, 1], dtype=int32)

In [15]:
np.max(minutes_n_ingredients[:,1:], axis=0) #максимум

array([2147483647,         39], dtype=int32)

In [16]:
np.median(minutes_n_ingredients[:,1:], axis=0)  #медиана

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [17]:
minutes_n_ingredients[minutes_n_ingredients[:, 1] < np.quantile(minutes_n_ingredients, 0.75, axis = 0)[1]]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [18]:
minutes_n_ingredients[minutes_n_ingredients[:,1] == 0].shape[0]

479

In [19]:
minutes_n_ingredients[:,1] = np.where((minutes_n_ingredients[:,1] == 0), 1, minutes_n_ingredients[:,1])
minutes_n_ingredients

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]], dtype=int32)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [20]:
np.size(np.unique(minutes_n_ingredients[:,1:], axis = 0))

8366

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [21]:
np.size(np.unique(minutes_n_ingredients[:,2], axis = 0)) #сколько

37

In [22]:
np.unique(minutes_n_ingredients[:,2], axis = 0) #какие

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39], dtype=int32)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [23]:
minutes_n_ingredients[minutes_n_ingredients[:,2] < 5]

array([[204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       ...,
       [227056,     30,      4],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [24]:
np.mean(minutes_n_ingredients[:, 2] / minutes_n_ingredients[:, 1])  # в среднем

0.381174261705681

In [25]:
np.max(minutes_n_ingredients[:, 2] / minutes_n_ingredients[:, 1])  # максимум

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [26]:
np.mean(np.sort(minutes_n_ingredients[:,1], axis = 0)[::-1][:100]) 

21518445.39

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [27]:
minutes_n_ingredients[np.random.randint(np.size(minutes_n_ingredients, axis = 0), size=10), :] #v1

array([[377522,     70,     14],
       [479450,    175,     17],
       [359622,     80,     12],
       [346440,    125,      3],
       [265996,      7,      5],
       [221509,     75,     17],
       [467738,     20,     10],
       [276069,      5,      5],
       [283808,     45,     11],
       [413579,     50,     13]], dtype=int32)

In [28]:
minutes_n_ingredients[np.random.choice(minutes_n_ingredients.shape[0], size=10, replace=False), :] #v2

array([[ 17679,     50,      7],
       [ 60029,     90,     12],
       [ 10984,     60,     16],
       [122669,      7,      4],
       [414250,     20,      7],
       [200116,     35,      9],
       [167188,    240,      8],
       [316787,     37,      6],
       [309127,     10,      9],
       [440702,     50,     16]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [29]:
slicee = minutes_n_ingredients[minutes_n_ingredients[:, 2] < np.mean(minutes_n_ingredients, axis = 0)[2]]
print(f'{(slicee.shape[0] / minutes_n_ingredients.shape[0]) * 100}%')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [30]:
condition = (minutes_n_ingredients[:, 1] <= 20) & (minutes_n_ingredients[:, 2] <= 5)
zeros = np.zeros((minutes_n_ingredients.shape[0],1), dtype='int32') 

minutes_n_ingredients_v2 = np.append(minutes_n_ingredients, zeros, axis=1)
minutes_n_ingredients_v2[:,3] = np.where(condition, 1, 0)
minutes_n_ingredients_v2

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [31]:
slicee = minutes_n_ingredients[minutes_n_ingredients[:, 2] < np.mean(minutes_n_ingredients, axis = 0)[2]]
ones = minutes_n_ingredients_v2[minutes_n_ingredients_v2[:,3] == 1].shape[0]
print(f'{(ones / minutes_n_ingredients_v2.shape[0]) * 100}%')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [32]:
# условия
short = minutes_n_ingredients[:, 1] < 10
medium = (minutes_n_ingredients[:, 1] >= 10) & (minutes_n_ingredients[:, 1] < 20)
long = minutes_n_ingredients[:, 1] >= 20

np.concatenate((minutes_n_ingredients[short], minutes_n_ingredients[medium], minutes_n_ingredients[long]), axis=0)

array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [287943,     85,     15],
       [498432,     65,     15],
       [ 81993,    140,     14]], dtype=int32)

In [33]:
short_m_n_i = minutes_n_ingredients[short]
short_m_n_i.sort(axis=0)
# short_m_n_i = np.vsplit(short_m_n_i[:,1:], short_m_n_i.shape[0])
short_m_n_i[-1]

array([536728,      9,     29], dtype=int32)

In [34]:
middle_m_n_i = minutes_n_ingredients[medium][:7588]
middle_m_n_i.sort(axis=0)
# middle_m_n_i = np.vsplit(middle_m_n_i[:,1:], middle_m_n_i.shape[0])
middle_m_n_i[-1]

array([532920,     19,     30], dtype=int32)

In [35]:
long_m_n_i = minutes_n_ingredients[long][:7588]
long_m_n_i.sort(axis=0)
# long_m_n_i = np.vsplit(long_m_n_i, long_m_n_i .shape[0])
long_m_n_i[-1]

array([536700,  43202,     35], dtype=int32)

In [36]:
# m_n_i_v3 = np.concatenate((short_m_n_i, middle_m_n_i, long_m_n_i), axis=0)
# m_n_i_v3 = np.vsplit(m_n_i_v3, 3)
m_n_i_v3 = np.stack((short_m_n_i[:,1:], middle_m_n_i[:,1:], long_m_n_i[:,1:]))
m_n_i_v3 

array([[[    1,     1],
        [    1,     1],
        [    1,     1],
        ...,
        [    9,    25],
        [    9,    28],
        [    9,    29]],

       [[   10,     1],
        [   10,     1],
        [   10,     2],
        ...,
        [   19,    25],
        [   19,    25],
        [   19,    30]],

       [[   20,     2],
        [   20,     2],
        [   20,     2],
        ...,
        [20175,    30],
        [23050,    30],
        [43202,    35]]], dtype=int32)

In [37]:
m_n_i_v3.ndim

3